# Generated by Django 6.0.6 on 2026-06-27 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=20, unique=True)),
                ('pan_number', models.CharField(max_length=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['gst_number'], name='clients_cli_gst_num_58ca2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('ca', 'gst_number'), name='unique_client_per_ca')],
            },
        ),
    ]
